### ISSUE TITLE
Buffered IO is about 3-4x slower than emp netio

### ISSUE THREAD

**Issue by xiangxiecrypto** [pado-labs/emp-rust#3]
Need to check out the implementation details.

**Comment by xiangxiecrypto** [comment]
emp c++ performance:
![image](https://github.com/pado-labs/emp-rust/assets/42728674/dc247cc1-5883-4ea5-a869-8f74fefe92be)

emp rust performance:
![image](https://github.com/pado-labs/emp-rust/assets/42728674/f431ce4f-256b-49b8-b18f-09e85149772d)

**Comment by ujnss** [comment]
The main reason is that the c++ version uses the memory address of the block array directly, while the rust version sends or receives blocks one by one.

Optimization.
When sending, convert block arrays to [u8] first. When receiving, receive [u8] and then convert to block array. See #11.

**Comment by xiangxiecrypto** [comment]
improved performance in emp-rust
<img width="725" alt="image" src="https://github.com/pado-labs/emp-rust/assets/42728674/c3e3c365-95ee-4fb6-938d-c5235b92974b">
